language: python
python:
    - 2.6
    - 2.7
install:
    - travis_retry pip install coverage coveralls -e .
script:
    - coverage run --source=mgp2pdf.py tests.py
after_success:
    - coveralls
notifications:
    email: false
